checksumBehavior: update

compressionLevel: 1

enableGlobalCache: true

enableImmutableInstalls: false

nodeLinker: node-modules

npmRegistryServer: 'https://registry.npmjs.org'

pnpMode: loose

#yarnPath: .yarn/releases/yarn-4.2.2.cjs
